### ISSUE TITLE
Working with VS2010?

### ISSUE THREAD

**Issue by Dawnkeeper** [adamralph/stylecop-msbuild#2]
I have set up one of our projects to use this package. Including the analysis before build option.

It works like charm on VS2015, but on a VS2010 I get the error "StyleCop target not found".

Is this an issue of the package or did I mess up the config?

**Comment by adamralph** [comment]
Hi @Dawnkeeper thanks for raising this issue.

I'm afraid I don't have VS2010 available to try it. Are you opening exactly the same solution/project in both VS2015 and VS2010?

**Comment by Dawnkeeper** [comment]
Yes, its the same solution shared via TFS.

**Comment by Dawnkeeper** [comment]
I poked around in the project for a while and finally found the solution: It was created in VS2015 but set to use only C#5 language features. As this language level is not available in VS2010 the compiler/msbuild seemingly couldn't handle it and decided to not shame itself and blame everything on StyleCop. After setting the language level to default everything worked again.

**Comment by adamralph** [comment]
@Dawnkeeper ok, great. Thanks for letting us know!
