### ISSUE TITLE
Ignores GlobalSuppressions.cs

### ISSUE THREAD

**Issue by agray** [adamralph/stylecop-msbuild#3]
As of version 4.7.49.1 (There appears to be no functional difference up to 4.7.54) adding a GlobalSuppressions,cs file to a solution or project appears to be totally ignored.

Please support GlobalSuppresions.cs as a way to specify rules once for an entire soliution that are to be suppressed

**Comment by adamralph** [comment]
Hi @agray, thanks for raising this.

Can you absolutely confirm that this works in 4.7.49.0 but not 4.7.49.1? StyleCop.MSBuild is largely just a repackaging of [StyleCop](https://stylecop.codeplex.com/) but a [subtle change](https://github.com/adamralph/stylecop-msbuild/commit/86abefbc38282a281a18b568b897db764d54da16) was added in 4.7.49.1. It doesn't make any reference to GlobalSupressions.cs but I'm wondering if this might be some undesirable side effect.

**Comment by agray** [comment]
Our VS2013 solution (at work) started with at 4.7.49.1.  Are you recommending we downgrade to 4.7.49.0?  Can this regression be addressed in a new version so we can upgrade easily?

**Comment by adamralph** [comment]
@agray no, I'm not suggesting you downgrade. From the way you phrased the question it sounded like you had noticed this regression when you upgraded to 4.7.49.1 from some earlier version.

As I said, this project is just a repackaging of [StyleCop](https://stylecop.codeplex.com/) and I'm not convinced that StyleCop has ever respected GlobalSupressions.cs. Have you observed that the StyleCop Visual Studio Extension does indeed respect GlobalSupressions.cs?

**Comment by agray** [comment]
Haven't seen the desired respect for GlobalSuppressions.cs.  From the looks of StackOverflow many people have been asking for it.  Is StyleCop a dead project?

**Comment by adamralph** [comment]
@agray StyleCop did go stale for a couple of years between 4.7.49.0 (April 2014) and 4.7.50.0 (February 2016). It now has a new group of owners and seems quite active. There have been 5 releases in the last 4 months.

I suggest you head over to https://stylecop.codeplex.com/ and enquire about support for `GlobalSupressions.cs` there. I'm afraid there's nothing we can do in StyleCop.MSBuild in that respect.

Again, thanks for raising this and please don't hesitate to raise more issues regarding StyleCop.MSBuild in the future.

**Comment by adamralph** [comment]
@agray of course, if a future version of StyleCop does introduce support for `GlobalSupression.cs`, we will pick up that new version and release a corresponding version of StyleCop.MSBuild containing that version of StyleCop.

**Comment by agray** [comment]
@adamralph Understood.  Good to hear StyleCop is active again.  I will contact them.

Thank you.

**Comment by agray** [comment]
You may close this

**Comment by agray** [comment]
See issue raised [here](https://stylecop.codeplex.com/workitem/7728).
